name: Release

on:
  release:
    types:
      - prereleased
      - released

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Deploy with Gradle
      run: ./gradlew --no-daemon -Pversion="${{github.event.release.tag_name}}" publish
      env:
        GRADLE_PUBLISH_REPO_URL: https://api.bintray.com/maven/spring/jars/BlockHound/
        GRADLE_PUBLISH_MAVEN_USER: ${{secrets.BINTRAY_USER}}
        GRADLE_PUBLISH_MAVEN_PASSWORD: ${{secrets.BINTRAY_API_KEY}}